# fly.toml app configuration file generated for burgerclicker on 2023-11-07T21:36:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "burgerclicker"
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
